### ISSUE TITLE
Problem installing on Tegra X1. aarch 64, nvcc fatal error

### ISSUE THREAD

**Issue by mehdifirouz** [UCI-CARL/CARLsim3#33]
Ubunto 14.04, Tegra X1 platform. Syetem Query test passed. NVCC version 7.0. CUDA_7.0 samples runs good

**Comment by mbeyeler** [comment]
I've been in contact with Mehdi. The problem is that `OS_SIZE` is not correctly extracted. It should be a number (32 or 64), but instead on your platform is aarch64.

Fix by replacing line 58:
https://github.com/UCI-CARL/CARLsim3/blob/master/carlsim/configure.mk#L58

with:

```
OS_SIZE = $(shell uname -m | sed -e "s/i.86/32/" -e "s/x86_64/64/" -e "s/armv7l/32/" -e "s/aarch64/64/")
```

Might apply to CARLsim 4, too.
